// Unified Mock Products Database for Raman Green

export interface Review {
  id: string;
  author: string;
  avatarInitials: string;
  rating: number;
  date: string;
  headline: string;
  text: string;
  images?: string[];
  helpfulCount: number;
  isVerified: boolean;
}

export interface ProductDetails {
  origin: string;
  prepTime: string;
  ingredients: string;
  nutrients: string[];
}

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  formattedPrice: string;
  originalPrice?: string;
  category: "seeds" | "crops" | "dry-foods" | "instant";
  categoryLabel: string;
  image: string;
  hoverImage?: string;
  tags: string[];
  details: ProductDetails;
  reviews: Review[];
}

export const productsData: Product[] = [
  {
    id: "1",
    name: "Heirloom Tomato Seeds",
    description: "Traditional non-hybrid organic tomato seeds handed down through generations, yielding rich flavor.",
    price: 8.0,
    formattedPrice: "₹640.00",
    originalPrice: "₹800.00",
    category: "seeds",
    categoryLabel: "Seeds",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1595855759920-86582396756a?w=600&q=80",
    tags: ["Heirloom", "High Yield"],
    details: {
      origin: "Rajasthan Orchards",
      prepTime: "Seasonal Sowing",
      ingredients: "100% Organic Tomato Seeds (Non-GMO)",
      nutrients: ["Purity Tested", "High Germination Rate", "Non-Hybrid Heritage"],
    },
    reviews: [
      {
        id: "r1",
        author: "Vikram S.",
        avatarInitials: "VS",
        rating: 5,
        date: "1 week ago",
        headline: "Exceptional Germination",
        text: "I sowed these seeds last week and almost all of them have sprouted healthy green leaves. Looking forward to a great harvest!",
        helpfulCount: 8,
        isVerified: true,
      },
    ],
  },
  {
    id: "2",
    name: "Organic White Quinoa",
    description: "Nutritious, high-protein white quinoa grains sourced from organic high-altitude farms.",
    price: 14.0,
    formattedPrice: "₹1,120.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&q=80",
    tags: ["High Protein", "Gluten Free"],
    details: {
      origin: "Andean Foothills / Rajasthan Organic Cooperative",
      prepTime: "15-Min Prep",
      ingredients: "100% Whole Grain White Quinoa",
      nutrients: ["Rich in Iron", "All 9 Essential Amino Acids", "High Dietary Fiber"],
    },
    reviews: [
      {
        id: "r2",
        author: "Meera K.",
        avatarInitials: "MK",
        rating: 4,
        date: "3 days ago",
        headline: "Super clean grain!",
        text: "Requires very little washing compared to other brands. Grains fluff up beautifully. Very satisfied.",
        helpfulCount: 5,
        isVerified: true,
      },
    ],
  },
  {
    id: "3",
    name: "Wild Rice Blend",
    description: "An elegant combination of premium long-grain brown rice and highly nutritious wild black rice.",
    price: 16.5,
    formattedPrice: "₹1,320.00",
    originalPrice: "₹1,500.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&q=80",
    tags: ["Organic", "Fiber Rich"],
    details: {
      origin: "Himalayan Wetlands",
      prepTime: "25-Min Prep",
      ingredients: "Organic Brown Rice, Wild Black Rice",
      nutrients: ["High Antioxidants", "Complex Carbohydrates", "Low Glycemic Index"],
    },
    reviews: [
      {
        id: "r3",
        author: "Rohan D.",
        avatarInitials: "RD",
        rating: 5,
        date: "1 month ago",
        headline: "Nutty and Delicious",
        text: "The texture is fantastic. It adds an earthy, nutty flavor to our meals. Excellent quality grains.",
        helpfulCount: 14,
        isVerified: true,
      },
    ],
  },
  {
    id: "4",
    name: "Genovese Basil Seeds",
    description: "Premium seeds for sweet, large-leaf Genovese basil. Ideal for home herb gardens and premium pesto.",
    price: 6.5,
    formattedPrice: "₹520.00",
    category: "seeds",
    categoryLabel: "Seeds",
    image: "https://images.unsplash.com/photo-1515471209610-dae1c92d8777?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=600&q=80",
    tags: ["High Germination", "Aromatic"],
    details: {
      origin: "Domestic Nursery",
      prepTime: "Year-Round Sowing",
      ingredients: "Premium Sweet Basil Seeds",
      nutrients: ["Aromatic Foliage", "Non-Treated Seeds", "Pesticide-Free"],
    },
    reviews: [],
  },
  {
    id: "5",
    name: "Heritage Rolled Oats",
    description: "100% whole grain organic oats rolled to perfection, preserving natural texture and fibers.",
    price: 12.0,
    formattedPrice: "₹960.00",
    originalPrice: "₹1,200.00",
    category: "crops",
    categoryLabel: "Crops",
    image: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1517881917430-e70dfb3610aa?w=600&q=80",
    tags: ["100% Organic", "Heart Healthy"],
    details: {
      origin: "Punjab Soil Co-op",
      prepTime: "5-Min Simmer",
      ingredients: "100% Organic Whole Grain Oats",
      nutrients: ["Beta-Glucan Soluble Fiber", "High Plant Protein", "Zero Preservatives"],
    },
    reviews: [
      {
        id: "r5",
        author: "Devendra P.",
        avatarInitials: "DP",
        rating: 5,
        date: "2 weeks ago",
        headline: "Proper old-school rolled oats",
        text: "These are thick and chewy, not the powdery instant stuff. Exactly what I was looking for. Perfect with cold milk or cooked.",
        helpfulCount: 9,
        isVerified: true,
      },
    ],
  },
  {
    id: "6",
    name: "French Green Lentils",
    description: "Rich, peppery green lentils imported from organic farms, holding their shape exceptionally when cooked.",
    price: 9.5,
    formattedPrice: "₹760.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1515942400420-2b98fed1f515?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1585559606132-277ba3031a6d?w=600&q=80",
    tags: ["Organic", "Iron Rich"],
    details: {
      origin: "Certified Organic Estates",
      prepTime: "20-Min Prep",
      ingredients: "100% Organic Green Lentils (Puy style)",
      nutrients: ["High Folate", "Plant-Based Iron", "Dense Dietary Fiber"],
    },
    reviews: [],
  },
  {
    id: "7",
    name: "Heirloom Black Chia Seeds",
    description: "Ethically sourced from the volcanic soils of the central highlands, our Heirloom Black Chia seeds are a nutritional powerhouse. Grounded in vitality, these seeds offer a crisp texture and a clean botanical profile, rich in Omega-3 and essential minerals.",
    price: 450,
    formattedPrice: "₹450",
    category: "seeds",
    categoryLabel: "Seeds",
    image: "https://images.unsplash.com/photo-1598030304671-5aa1d6f21128?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&q=80",
    tags: ["High Fiber", "Vegan", "Organic"],
    details: {
      origin: "Rajasthan Farms",
      prepTime: "Instant Prep / Soak",
      ingredients: "100% Raw Organic Chia Seeds",
      nutrients: ["Rich in Omega-3 Alpha-Linolenic Acid", "High Calcium & Magnesium", "Powerful Antioxidants"],
    },
    reviews: [
      {
        id: "r7_1",
        author: "Anya R.",
        avatarInitials: "AR",
        rating: 5,
        date: "2 weeks ago",
        headline: "Purity you can taste",
        text: "The texture of these chia seeds is significantly better than store-bought brands. They gel up perfectly for my overnight pudding and the flavor is so clean. Definitely worth the heirloom price.",
        images: [
          "https://images.unsplash.com/photo-1598030304671-5aa1d6f21128?w=300&q=80",
          "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=300&q=80"
        ],
        helpfulCount: 12,
        isVerified: true,
      },
      {
        id: "r7_2",
        author: "Siddharth M.",
        avatarInitials: "SM",
        rating: 4.5,
        date: "3 weeks ago",
        headline: "Excellent Superfood Quality",
        text: "I add these to my post-workout smoothies every single day. Extremely clean seeds with virtually no dirt or stones. Will definitely reorder.",
        helpfulCount: 7,
        isVerified: true,
      },
    ],
  },
  {
    id: "8",
    name: "Kashmiri Walnut Kernels",
    description: "100% organic, hand-shelled light walnut halves from traditional family orchards in Kashmir.",
    price: 18.0,
    formattedPrice: "₹1,440.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1585559606132-277ba3031a6d?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&q=80",
    tags: ["Heirloom", "Brain Health"],
    details: {
      origin: "Kashmir Valley Orchards",
      prepTime: "Ready to Eat",
      ingredients: "100% Hand-Shelled Walnut Kernels",
      nutrients: ["Omega-3 Fatty Acids", "Brain-boosting Antioxidants", "Copper & Manganese"],
    },
    reviews: [
      {
        id: "r8",
        author: "Arjun S.",
        avatarInitials: "AS",
        rating: 5,
        date: "4 days ago",
        headline: "So fresh and buttery!",
        text: "Absolutely premium quality halves. They are not bitter at all, indicating they are very fresh. Sourced straight from Kashmir, tastes incredibly buttery.",
        helpfulCount: 10,
        isVerified: true,
      },
    ],
  },
  {
    id: "9",
    name: "Organic Millet Muesli",
    description: "Crunchy multigrain muesli sweetened with real dried fruit chunks and wild mountain honey.",
    price: 15.0,
    formattedPrice: "₹1,200.00",
    category: "instant",
    categoryLabel: "Instant",
    image: "https://images.unsplash.com/photo-1517881917430-e70dfb3610aa?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80",
    tags: ["Organic", "No Refined Sugar"],
    details: {
      origin: "Rajasthan Orchards & Grains",
      prepTime: "Quick 3-Min Prep",
      ingredients: "Organic Pearl Millet, Ragi, Rolled Oats, Honey, Dried Berries, Nuts",
      nutrients: ["High Fiber Grains", "Naturally Sweetened", "Iron & Calcium Rich"],
    },
    reviews: [
      {
        id: "r9",
        author: "Priya V.",
        avatarInitials: "PV",
        rating: 5,
        date: "2 weeks ago",
        headline: "Superb healthy breakfast",
        text: "Perfect crunch and balanced sweetness. I love that it uses local millets like bajra and ragi instead of cornflakes. Super healthy morning start!",
        helpfulCount: 15,
        isVerified: true,
      },
    ],
  },
  {
    id: "10",
    name: "Organic Golden Flaxseeds",
    description: "Nutty, high-fiber golden flaxseeds. Perfect for adding to smoothies, baking, and morning oats.",
    price: 9.0,
    formattedPrice: "₹720.00",
    category: "seeds",
    categoryLabel: "Seeds",
    image: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1598030304671-5aa1d6f21128?w=600&q=80",
    tags: ["Pure Organic", "Omega-3 Rich"],
    details: {
      origin: "Madhya Pradesh Plains",
      prepTime: "Ground or Whole",
      ingredients: "100% Organic Golden Flaxseeds",
      nutrients: ["High Soluble & Insoluble Fiber", "Lignans for Heart Health", "Plant Omega-3s"],
    },
    reviews: [],
  },
  {
    id: "11",
    name: "Premium Roasted Almonds",
    description: "Salted roasted whole almonds loaded with natural goodness and crunchy flavor.",
    price: 14.5,
    formattedPrice: "₹1,160.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1585559606132-277ba3031a6d?w=600&q=80",
    tags: ["Best Seller", "Protein Rich"],
    details: {
      origin: "Organic Almond Groves",
      prepTime: "Snack Ready",
      ingredients: "Organic Whole Almonds, Rock Salt",
      nutrients: ["Vitamin E (Antioxidant)", "Healthy Monounsaturated Fats", "High Plant-Based Protein"],
    },
    reviews: [],
  },
  {
    id: "12",
    name: "Ready-to-Cook Quinoa Mix",
    description: "A pre-seasoned organic quinoa and herb mix. Preps in 15 minutes for a healthy side or main meal.",
    price: 11.0,
    formattedPrice: "₹880.00",
    category: "instant",
    categoryLabel: "Instant",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80",
    tags: ["Quick Prep", "100% Natural"],
    details: {
      origin: "Organic Farms Collective",
      prepTime: "15-Min One-Pot",
      ingredients: "Organic Quinoa, Dehydrated Herbs (Parsley, Oregano), Onion, Garlic, Sea Salt",
      nutrients: ["Complete Protein", "Low Sodium", "High Magnesium"],
    },
    reviews: [],
  },
  {
    id: "13",
    name: "Sun-Dried Heirloom Figs",
    description: "Naturally sweet, un-sulfured figs packed with essential minerals and energy.",
    price: 25.0,
    formattedPrice: "₹1,120.00",
    originalPrice: "₹1,600.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1601379327928-bedfaf9da2d0?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=600&q=80",
    tags: ["No Added Sugar", "Iron Rich"],
    details: {
      origin: "Rajasthan Orchards",
      prepTime: "Ready to Eat",
      ingredients: "100% Sun-Dried Heirloom Figs",
      nutrients: ["High Dietary Fiber", "Excellent Source of Calcium & Iron", "Natural Glucose and Fructose"],
    },
    reviews: [
      {
        id: "r13",
        author: "Karan J.",
        avatarInitials: "KJ",
        rating: 5,
        date: "3 weeks ago",
        headline: "Incredibly sweet and moist!",
        text: "Unlike the dry, hard figs you get elsewhere, these are plump, chewy, and naturally so sweet. Excellent product!",
        helpfulCount: 6,
        isVerified: true,
      },
    ],
  },
  {
    id: "14",
    name: "Morning Ritual Oat Bowl",
    description: "A balanced blend of golden flax oats, nuts, seeds, and superfoods ready in 3 minutes.",
    price: 3.75,
    formattedPrice: "₹240.00",
    originalPrice: "₹320.00",
    category: "instant",
    categoryLabel: "Instant",
    image: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1598030304671-5aa1d6f21128?w=600&q=80",
    tags: ["Gluten Free", "Quick Prep"],
    details: {
      origin: "Artisanal Blenders Co.",
      prepTime: "Quick 3-Min Prep",
      ingredients: "Organic Golden Oats, Flaxseeds, Sunflower Seeds, Almond Slivers, Chia",
      nutrients: ["Superfood Nutrient Pack", "Zero Added Sugar", "Complex Carbs for Steady Energy"],
    },
    reviews: [
      {
        id: "r14",
        author: "Aditi G.",
        avatarInitials: "AG",
        rating: 5,
        date: "10 days ago",
        headline: "My daily breakfast ritual!",
        text: "Literally takes 3 minutes. I splash hot almond milk on it, add half a banana, and I am set for the day. Tastes super clean and organic.",
        helpfulCount: 11,
        isVerified: true,
      },
    ],
  },
  {
    id: "15",
    name: "Cold-Pressed Mustard Honey",
    description: "Unprocessed, single-origin raw honey harvested sustainably from organic farms.",
    price: 15.0,
    formattedPrice: "₹1,200.00",
    originalPrice: "₹1,500.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&q=80",
    tags: ["Raw & Pure", "Single Origin"],
    details: {
      origin: "Rajasthan Orchards Honeycomb",
      prepTime: "Raw Consumption",
      ingredients: "100% Raw Unfiltered Mustard Honey",
      nutrients: ["Active Natural Enzymes", "Rich in Pollen & Phytonutrients", "Natural Antibacterial Action"],
    },
    reviews: [],
  },
  {
    id: "16",
    name: "Organic Bajra Flour",
    description: "Stone-ground organic pearl millet flour. High in protein, fiber, and essential minerals.",
    price: 11.25,
    formattedPrice: "₹900.00",
    originalPrice: "₹1,150.00",
    category: "crops",
    categoryLabel: "Crops",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80",
    tags: ["Gluten Free", "Iron Rich"],
    details: {
      origin: "Traditional stone mills in Rajasthan",
      prepTime: "Baking / Cooking",
      ingredients: "100% Organic Pearl Millet (Bajra) Grains",
      nutrients: ["High Plant Protein", "Slow-release Carbohydrates", "Rich in Magnesium & Iron"],
    },
    reviews: [],
  },
  {
    id: "17",
    name: "Cold-Pressed Sesame Oil",
    description: "Traditional wood-pressed white sesame oil, rich in flavor, antioxidants and nutrients.",
    price: 30.0,
    formattedPrice: "₹2,400.00",
    originalPrice: "₹3,000.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80",
    tags: ["Wood Pressed", "Heart Healthy"],
    details: {
      origin: "Traditional wood presses (Ghani)",
      prepTime: "Cooking / Seasoning",
      ingredients: "100% Wood Pressed White Sesame Seeds",
      nutrients: ["Sesamol & Sesamin Antioxidants", "Balanced Omega-6 & Omega-9 Fats", "Vitamin E Rich"],
    },
    reviews: [],
  },
  {
    id: "18",
    name: "A2 Gir Cow Ghee",
    description: "Pure Vedic A2 ghee made from high-quality Gir cow milk using the traditional Bilona method.",
    price: 125.0,
    formattedPrice: "₹9,990.00",
    originalPrice: "₹12,500.00",
    category: "dry-foods",
    categoryLabel: "Dry Foods",
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
    tags: ["Bilona Method", "Vedic A2"],
    details: {
      origin: "Vedic Goshala",
      prepTime: "Culinary Use",
      ingredients: "100% A2 Cultured Cow Butterfat",
      nutrients: ["Short and Medium Chain Fatty Acids", "Butyric Acid for Gut Health", "Fat-soluble Vitamins A, D, E, K"],
    },
    reviews: [
      {
        id: "r18",
        author: "Dr. Rajesh R.",
        avatarInitials: "RR",
        rating: 5,
        date: "2 months ago",
        headline: "Purest traditional ghee available!",
        text: "The aroma is outstanding, remind me of my childhood days in the village. Genuine Bilona ghee, granular texture is perfect. Highly recommended for Ayurvedic rituals and daily cooking.",
        helpfulCount: 22,
        isVerified: true,
      },
    ],
  },
];
